[package]
name = "veil-fuse"
version = "0.1.0"
edition.workspace = true

[dependencies]
veil-core = { path = "../veil-core" }

# FUSE 实现
fuser = "0.15"

# 异步运行时
tokio = { version = "1", features = ["sync", "rt"] }

# 日志
tracing = "0.1"

# 错误处理
thiserror = "2"
anyhow = "1"

# 系统调用
libc = "0.2"

[dev-dependencies]
tracing-subscriber = "0.3"
rpassword = "7"
